version: '3'
services:

  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/laravel.nginx:/opt/bitnami/nginx/conf/server_blocks/laravel.conf
      - ./laravel:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=Root.4lab
      - MARIADB_DATABASE=mining
      - MARIADB_USER=smashed
      - MARIADB_PASSWORD=User.4lab
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/bitnami/mariadb/data

  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - ./laravel/:/app
#    links:
#      - mailcatcher:mailcatcher
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=mining
      - DB_USERNAME=smashed
      - DB_PASSWORD=User.4lab

#  redis:
#    image: bitnami/redis:latest
#    ports:
#      - 63790:6379
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    restart: always
#    depends_on:
#      - redis
#    links:
#    - redis:redis
#    environment:
#    - REDIS_HOSTS=local:redis:6379
#    ports:
#    - 8091:8081     # web interface, hit localhost:8091 to explore redis
#  mailcatcher:
#    image: tophfr/mailcatcher
#    ports:
#      - 1081:80   # web interface, hit localhost:1080 to see the mails
#      - 1025:25   # expose port 1025 so we can send emails from the host machine as well

