version: '3.4'
services:

  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/laravel.nginx:/opt/bitnami/nginx/conf/server_blocks/laravel.conf
      - lara_data:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - BITNAMI_DEBUG=true
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/bitnami/mariadb/data

  php-fpm:
    image: nesfit/jane-smashed:1.1
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    environment:
      - PMA_HOST=mariadb
    volumes:
      - lara_data:/app
      - ./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
    depends_on:
      - mariadb
  
  api-server:
    image: node:16
    build:
      context: ./api-server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mariadb
      - DB=${MARIADB_DATABASE}
      - DB_USER=${MARIADB_USER}
      - DB_PWD=${MARIADB_PASSWORD}
    volumes:
      - ./api-server/data:/app/data
    depends_on:
      - mariadb

volumes:
  lara_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/php-fpm/data"

networks:
  default:
    external:
      name: ${NETWORK}


x-logging:
  driver: json-file
  options:
    max-size: '20m'
    max-file: '5'
